name: Trigger Lambda on GitHub Update

on:
  push:
    branches:
      - main
      - master

jobs:
  call-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Gateway to trigger Lambda
        run: |
          curl -X GET "https://7kfyx1527c.execute-api.ap-northeast-1.amazonaws.com/default/screenshot"
